functional:
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины;
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре;
  - Сайт должен быть доступен на различных устройствах;
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории;
  - Пользователь должен иметь возможность фильтровать товары;

non-functional:
   - Сайт должен быть удобным для использования;
   - Сайт должен быть безопасным и защищать данные пользователя;
   - Сайт должен быть оптимизирован для скорости работы;
   - Сайт должен обрабатывать большое количество трафика;
   - Сайт должен быть протестирован на совместимость с последними версиями браузеров;
   - Сайт должен быть доступен на различных устройствах;

implicit:
   - Интерфейс должен быть интуитивно понятным для пользователей;
   - Время загрузки страниц должно быть минимальным для улучшения пользовательского опыта;
   - Сайт должен поддерживать актуальные стандарты безопасности;
